collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9686146
  brandStrength: 1
  lightness: 0.4229391
  brandColors:
    - '#010101'
    - '#F5F4F2'
    - '#AEB0A5'
    - '#373526'
    - '#715639'
  rhythmicContrast: 1
typography_spectrum: 0.4623656
layout_spectrum: 1
name: Heldenkg
