layout_spectrum: 1
color:
  saturation: 0.9686146
  lightness: 0.2447009
  brandStrength: 1
  brandColors:
    - '#C2C2BA'
    - '#15181D'
    - '#FFFFFF'
    - '#383836'
    - '#96968C'
  rhythmicContrast: 1
typography_spectrum: 0.5340502
name: Heldenkg
